%def op_invoke_custom():
    break 0x5

%def op_invoke_custom_range():
    break 0x5

%def invoke_direct_or_super(helper="", range="", is_super=""):
    break 0x5

%def op_invoke_direct():
    break 0x5

%def op_invoke_direct_range():
    break 0x5

%def op_invoke_super():
    break 0x5

%def op_invoke_super_range():
    break 0x5

%def op_invoke_polymorphic():
    break 0x5

%def op_invoke_polymorphic_range():
    break 0x5

%def invoke_interface(range=""):
    break 0x5

%def op_invoke_interface_slow_path():
    break 0x5

%def op_invoke_interface():
    break 0x5

%def op_invoke_interface_range():
    break 0x5

%def invoke_static(helper=""):
    break 0x5

%def op_invoke_static():
    break 0x5

%def op_invoke_static_range():
    break 0x5

%def invoke_virtual(helper="", range=""):
    break 0x5

%def op_invoke_virtual():
    break 0x5

%def op_invoke_virtual_range():
    break 0x5
