%def op_check_cast():
    break 0x5

%def op_check_cast_slow_path():
    break 0x5

%def op_instance_of():
    break 0x5

%def op_instance_of_slow_path():
    break 0x5

%def op_iget_boolean():
    break 0x5

%def op_iget_byte():
    break 0x5

%def op_iget_char():
    break 0x5

%def op_iget_short():
    break 0x5

%def op_iget(load="", wide="", is_object=""):
    break 0x5

%def op_iget_slow_path(load, wide, is_object):
    break 0x5

%def op_iget_wide():
    break 0x5

%def op_iget_object():
    break 0x5

%def op_iput_boolean():
    break 0x5

%def op_iput_byte():
    break 0x5

%def op_iput_char():
    break 0x5

%def op_iput_short():
    break 0x5

%def op_iput(store="", wide="", is_object=""):
    break 0x5

%def op_iput_slow_path(store, wide, is_object):
    break 0x5

%def op_iput_wide():
    break 0x5

%def op_iput_object():
    break 0x5

%def op_sget_boolean():
    break 0x5

%def op_sget_byte():
    break 0x5

%def op_sget_char():
    break 0x5

%def op_sget_short():
    break 0x5

%def op_sget(load="", wide="", is_object=""):
    break 0x5

%def op_sget_slow_path(load, wide, is_object):
    break 0x5

%def op_sget_wide():
    break 0x5

%def op_sget_object():
    break 0x5

%def op_sput_boolean():
    break 0x5

%def op_sput_byte():
    break 0x5

%def op_sput_char():
    break 0x5

%def op_sput_short():
    break 0x5

%def op_sput(store="", wide="", is_object=""):
    break 0x5

%def op_sput_slow_path(store, wide, is_object):
    break 0x5

%def op_sput_wide():
    break 0x5

%def op_sput_object():
    break 0x5

%def op_new_instance():
    break 0x5
